[package]
name = "corroded_dav_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustydav = "0.1.3"
url = "2.3.1"
rustyline = "11.0.0"
minidom = "0.15.1"
derive_more = "0.99.17"
